List<String> states = [
  'Abia',
  'Adamawa',
  'Akwa Ibom',
  'Anambra',
  'Bauchi',
  'Bayelsa',
  'Benue',
  'Borno',
  'Cross River',
  'Delta',
  'Ebonyi',
  'Edo',
  'Ekiti',
  'Enugu',
  'Gombe',
  'Imo',
  'Jigawa',
  'Kaduna',
  'Kano',
  'Katsina',
  'Kebbi',
  'Kogi',
  'Kwara',
  'Lagos',
  'Nasarawa',
  'Niger',
  'Ogun',
  'Ondo',
  'Osun',
  'Oyo',
  'Plateau',
  'Rivers',
  'Sokoto',
  'Taraba',
  'Yobe',
  'Zamfara',
  'Federal Capital Territory',
];

Map<String, List<String>> localGovernments = {
  'Abia': [
    'Aba North',
    'Aba South',
    'Arochukwu',
    'Bende',
    'Ikwuano-Umuahia',
    'Isiala Ngwa North',
    'Isiala Ngwa South',
    'Isuikwuato',
    'Obingwa',
    'Ohafia',
    'Osisioma Ngwa',
    'Umuahia North',
    'Umuahia South',
    'Umu Nneochi',
  ],
  'Adamawa': [
    'Demsa',
    'Fufure',
    'Ganye',
    'Girei',
    'Hong',
    'Jada',
    'Lamurde',
    'Madagali',
    'Maiha',
    'Mayo-Belwa',
    'Michika',
    'Mubi North',
    'Mubi South',
    'Numan',
    'Shelleng',
    'Song',
    'Yola North',
    'Yola South',
  ],
  'Akwa Ibom': [
    'Abak',
    'Eastern Obolo',
    'Eket',
    'Esit Eket',
    'Essien Udim',
    'Etim Ekpo',
    'Etinan',
    'Ibeno',
    'Ibesikpo Asutan',
    'Ibiono-Ibom',
    'Ika',
    'Ikono',
    'Ikot Abasi',
    'Ikot Ekpene',
    'Ini',
    'Itu',
    'Mbo',
    'Mkpat-Enin',
    'Nsit Atai',
    'Nsit Ibom',
    'Nsit Ubium',
    'Obot Akara',
    'Okobo',
    'Onna',
    'Oron',
    'Oruk Anam',
    'Udung Uko',
    'Ukanafun',
    'Uruan',
    'Uyo',
  ],
  'Anambra': [
    'Aguata',
    'Anambra East',
    'Anambra West',
    'Anaocha',
    'Awka North',
    'Awka South',
    'Ayamelum',
    'Dunukofia',
    'Ekwusigo',
    'Idemili North',
    'Idemili South',
    'Ihiala',
    'Njikoka',
    'Nnewi North',
    'Nnewi South',
    'Ogbaru',
    'Okafor Ofu',
    'Onitsha North',
    'Onitsha South',
    'Orumba North',
    'Orumba South',
    'Oyi',
  ],
  'Bauchi': [
    'Alkaleri',
    'Bauchi',
    'Bogoro',
    'Damban',
    'Darazo',
    'Dass',
    'Gamawa',
    'Ganjuwa',
    'Giade',
    'Itas/Gadau',
    'Jama’are',
    'Katagum',
    'Kirfi',
    'Misau',
    'Ningi',
    'Tafawa Balewa',
    'Toro',
    'Warji',
    'Zaki',
  ],
  'Bayelsa': [
    'Brass',
    'Ekeremor',
    'Kolokuma/Opokuma',
    'Nembe',
    'Ogbia',
    'Sagbama',
    'Southern Ijaw',
  ],
  'Benue': [
    'Agatu',
    'Apa',
    'Ado',
    'Benue',
    'Gboko',
    'Guma',
    'Gwer East',
    'Gwer West',
    'Katsina-Ala',
    'Konshisha',
    'Kwande',
    'Logo',
    'Makurdi',
    'Obi',
    'Ogbadibo',
    'Ohimini',
    'Okpokwu',
    'Otukpo',
    'Tarka',
  ],
  'Borno': [
  'Abadam',
  'Abadam',
  'Askira-Uba',
  'Bama',
  'Bayo',
  'Biu',
  'Chibok',
  'Damboa',
  'Dikwa',
  'Gubio',
  'Guzamala',
  'Gwoza',
  'Hawul',
  'Jere',
  'Kaga',
  'Kala/Balge',
  'Konduga',
  'Kukawa',
  'Kwaya Kusar',
  'Mafa',
  'Magumeri',
  'Maiduguri',
  'Marte',
  'Mobbar',
  'Monguno',
  'Ngala',
  'Nganzai',
  'Shani',],
  'Cross River': ['Abi',
    'Akamkpa',
    'Akpabuyo',
    'Bakassi',
    'Bekwarra',
    'Biase',
    'Boki',
    'Calabar Municipal',
    'Calabar South',
    'Etung',
    'Ikom',
    'Obanliku',
    'Obubra',
    'Obudu',
    'Odukpani',
    'Ogoja',
    'Yakurr',
    'Yala',],
  'Delta': [
    'Aniocha North',
    'Aniocha South',
    'Bomadi',
    'Burutu',
    'Ethiope East',
    'Ethiope West',
    'Ika North East',
    'Ika South',
    'Isoko North',
    'Isoko South',
    'Ndokwa East',
    'Ndokwa West',
    'Okpe',
    'Oshimili North',
    'Oshimili South',
    'Patani',
    'Sapele',
    'Udu',
    'Ughelli North',
    'Ughelli South',
    'Ukwuani',
  ],
   'Ebonyi': [
'Abakaliki',
'Afikpo North',
'Afikpo South (Edda)',
'Ebonyi',
'Ezza North',
'Ezza South',
'Ikwo',
'Ishielu',
'Ivo',
'Izzi',
'Ohaozara',
'Ohaukwu',
'Onicha',
],
'Edo': [
'Egor',
'Esan Central',
'Esan East',
'Esan North-East',
'Esan South-East',
'Esan West',
'Etsako Central',
'Etsako East',
'Etsako West',
'Igueben',
'Ikpoba Okha',
'Orhionmwon',
'Ovia North-East',
'Ovia South-West',
'Uvwie',
],
'Ekiti': [
'Ado Ekiti',
'Efon',
'Ekiti East',
'Ekiti South-West',
'Ekiti West',
'Emure',
'Gbonyin',
'Ido Osi',
'Ijero',
'Ikere',
'Ise/Orun',
'Moba',
'Oye',
],
'Enugu': [
'Aninri',
'Awgu',
'Enugu East',
'Enugu North',
'Enugu South',
'Ezeagu',
'Igbo-Etiti',
'Igbo-Eze North',
'Igbo-Eze South',
'Isi Uzo',
'Nkanu East',
'Nkanu West',
'Oji-River',
'Udenu',
'Udi',
],
'Gombe': [
'Akko',
'Billiri',
'Dukku',
'Funakaye',
'Gombe',
'Kaltungo',
'Kwami',
'Shongom',
'Yamaltu/Deba',
],
'Imo': [
'Aboh Mbaise',
'Ahiazu Mbaise',
'Ehime Mbano',
'Emekuku',
'Ihitte Uboma',
'Ikeduru',
'Isu',
'Mbaitoli',
'Ngor Okpala',
'Njaba',
'Nkwerre',
'Nwangele',
'Oguta',
'Ohaji/Egbema',
'Okigwe',
'Onuimo',
'Orlu',
'Oru East',
'Oru West',
'Owerri Municipal',
'Owerri North',
'Owerri West',
'Unuimo',
],
'Jigawa': [
'Auyo',
'Babura',
'Birnin Kudu',
'Dutse',
'Garki',
'Gumel',
'Guri',
'Hadejia',
'Jahun',
'Kafin Hausa',
'Kaugama',
'Kazaure',
'Kiri Kasama',
'Maigatari',
'Malam Madori',
'Ringim',
'Taura',
'Yankwashi',
],
  'Kaduna': [
    'Birnin Gwari',
'Chikun',
'Giwa',
'Igabi',
'Ikara',
'Jaba',
'Jere',
'Kajuru',
'Kaura',
'Kauru',
'Kubau',
'Kudan',
'Lere',
'Makarfi',
'Sabon Gari',
'Sanga',
'Soba',
'Zangon Kataf',
'Zaria',
],
  'Kano': [
    'Ajingi',
    'Albasu',
    'Bebeji',
    'Bichi',
    'Dala',
    'Dawakin Kudu',
    'Fagge',
    'Gabasawa',
    'Garko',
    'Garum Malam',
    'Gaya',
    'Gezawa',
    'Gwale',
    'Kano Municipal',
    'Karaye',
    'Kibiya',
    'Kiru',
    'Kumbotso',
    'Kunchi',
    'Kura',
    'Madobi',
    'Makoda',
    'Minjibir',
    'Nasarawa',
    'Rogo',
    'Rimin Gado',
    'Sumaila',
    'Takai',
    'Tarauni',
    'Tofa',
    'Tureta',
    'Ungogo',
    'Warawa',
  ],
  'Katsina': [
    'Bakori',
    'Batagarawa',
    'Batsari',
    'Baure',
    'Bindawa',
    'Charanchi',
    'Daura',
    'Dutsi',
    'Faskari',
    'Funtua',
    'Jibia',
    'Kafur',
    'Kankara',
    'Kankia',
    'Katsina',
    'Kurfi',
    'Kusada',
    'Mai’adua',
    'Malumfashi',
    'Mani',
    'Mashi',
    'Matazu',
    'Musawa',
    'Rimi',
    'Sandamu',
    'Zango',
  ],
  'Kebbi': [
    'Aleiro',
    'Arewa Dandi',
    'Argungu',
    'Augie',
    'Bagudo',
    'Birnin Kebbi',
    'Bunza',
    'Dandi',
    'Fakai',
    'Gwandu',
    'Jega',
    'Kalgo',
    'Koko/Besse',
    'Maiyama',
    'Ngaski',
    'Sakaba',
    'Shanga',
    'Suru',
    'Wasagu/Danko',
    'Yauri',
    'Zuru',
  ],
  'Kogi': [
    'Adavi',
    'Ajaokuta',
    'Ankpa',
    'Bassa',
    'Dekina',
    'Ibaji',
    'Idah',
    'Igalamela-Odolu',
    'Ijumu',
    'Kabba/Bunu',
    'Kogi',
    'Lokoja',
    'Mopa-Muro',
    'Ofu',
    'Ogori-Magongo',
    'Okehi',
    'Okene',
    'Olamaboro',
    'Omala',
    'Yagba East',
    'Yagba West',
  ],
  'Kwara': [
    'Asa',
    'Baruten',
    'Ede',
    'Ifelodun',
    'Ilorin East',
    'Ilorin South',
    'Ilorin West',
    'Irepodun',
    'Isin',
    'Kaiama',
    'Moro',
    'Offa',
    'Oke Ero',
    'Oyun',
    'Patigi',
  ],
  'Lagos': [
    'Agege',
    'Ajeromi-Ifelodun',
    'Alimosho',
    'Amuwo-Odofin',
    'Apapa',
    'Badagry',
    'Ebute Metta',
    'Eti-Osa',
    'Ibeju-Lekki',
    'Ifako-Ijaye',
    'Ikeja',
    'Ikorodu',
    'Kosofe',
    'Lagos Island',
    'Lagos Mainland',
    'Mushin',
    'Ojo',
    'Oshodi-Isolo',
    'Somolu',
    'Surulere',
    'Yaba',
  ],
  'Nasarawa': [
    'Akwanga',
    'Awe',
    'Doma',
    'Karu',
    'Keffi',
    'Kokona',
    'Lafia',
    'Nasarawa',
    'Nasarawa Egon',
    'Obi',
    'Toto',
    'Wamba',
  ],
  'Niger': [
    'Agaie',
    'Agwara',
    'Bida',
    'Borgu',
    'Bosso',
    'Chanchaga',
    'Edati',
    'Gbako',
    'Gurara',
    'Lapai',
    'Lavun',
    'Magama',
    'Mariga',
    'Mashegu',
    'Mokwa',
    'Muya',
    'Pategi',
    'Rafi',
    'Shiroro',
    'Suleja',
    'Tafawa Balewa',
  ],
  'Ogun': [
    'Abeokuta North',
    'Abeokuta South',
    'Ado-Odo/Ota',
    'Egbado North',
    'Egbado South',
    'Ewekoro',
    'Ifo',
    'Ijebu East',
    'Ijebu North',
    'Ijebu North East',
    'Ijebu Ode',
    'Ikenne',
    'Ipokia',
    'Odeda',
    'Ogun Waterside',
    'Remo North',
    'Remo South',
  ],
  'Ondo': [
    'Akoko North-East',
    'Akoko North-West',
    'Akoko South-Akure',
    'Akoko South-East',
    'Akure North',
    'Akure South',
    'Ese Odo',
    'Idanre',
    'Ifedore',
    'Ilaje',
    'Ile Oluji/Okeigbo',
    'Irele',
    'Odigbo',
    'Okitipupa',
    'Ondo East',
    'Ondo West',
    'Ose',
    'Owo',
  ],
  'Osun': [
    'Atakunmosa East',
    'Atakunmosa West',
    'Ayedaade',
    'Ayedire',
    'Boluwaduro',
    'Boripe',
    'Ede North',
    'Ede South',
    'Egbedore',
    'Ejigbo',
    'Ife Central',
    'Ife East',
    'Ife North',
    'Ife South',
    'Ila',
    'Ilesa East',
    'Ilesa West',
    'Irepodun',
    'Iwo',
    'Obokun',
    'Odo Otin',
    'Ola Oluwa',
    'Olorunda',
    'Oriade',
    'Orolu',
    'Osogbo',
  ],
  'Oyo': [
    'Afijio',
    'Akinyele',
    'Atiba',
    'Atisbo',
    'Egbeda',
    'Ibadan North',
    'Ibadan North-East',
    'Ibadan North-West',
    'Ibadan South-East',
    'Ibadan South-West',
    'Ibarapa Central',
    'Ibarapa East',
    'Ibarapa North',
    'Ido',
    'Irepo',
    'Iseyin',
    'Itesiwaju',
    'Iwajowa',
    'Kajola',
    'Lagelu',
    'Ogbomosho North',
    'Ogbomosho South',
    'Ogo Oluwa',
    'Olorunsogo',
    'Oluyole',
    'Ona Ara',
    'Ori Ire',
    'Oyo East',
    'Oyo West',
  ],
  'Plateau': [
    'Bokkos',
    'Jos East',
    'Jos North',
    'Jos South',
    'Kanam',
    'Kanke',
    'Langtang North',
    'Langtang South',
    'Mangu',
    'Mikang',
    'Pankshin',
    'Qua’an Pan',
    'Riyom',
    'Shendam',
    'Wase',
  ],
  'Rivers': [
    'Abua/Odual',
    'Ahoada East',
    'Ahoada West',
    'Akuku-Toru',
    'Andoni',
    'Asari-Toru',
    'Bonny',
    'Degema',
    'Eleme',
    'Emohua',
    'Etche',
    'Gokana',
    'Ikwerre',
    'Khana',
    'Obio/Akpor',
    'Ogba/Egbema/Ndoni',
    'Ogu/Bolo',
    'Okrika',
    'Opobo/Nkoro',
    'Oyigbo',
    'Port Harcourt',
  ],
  'Sokoto': [
    'Binji',
    'Bodinga',
    'Dange-Shuni',
    'Gada',
    'Goronyo',
    'Gudu',
    'Illela',
    'Isa',
    'Kebbe',
    'Kware',
    'Rabah',
    'Sabon Birni',
    'Shagari',
    'Silame',
    'Sokoto North',
    'Sokoto South',
    'Tambuwal',
    'Tureta',
    'Wamako',
    'Wurno',
    'Yabo',
  ],
  'Taraba': [
    'Ardo-Kola',
    'Bali',
    'Donga',
    'Gashaka',
    'Gassol',
    'Ibi',
    'Jalingo',
    'Karim Lamido',
    'Kurmi',
    'Lau',
    'Sardauna',
    'Takum',
    'Ussa',
    'Wukari',
  ],
  'Yobe': [
    'Bade',
    'Bursari',
    'Damaturu',
    'Fika',
    'Fune',
    'Geidam',
    'Gujba',
    'Gulani',
    'Jakusko',
    'Karasuwa',
    'Machina',
    'Nangere',
    'Nguru',
    'Potiskum',
    'Tarmuwa',
    'Yunusari',
  ],
  'Zamfara': [
    'Anka',
    'Bakura',
    'Birnin Magaji/Kiyawa',
    'Bukkuyum',
    'Bungudu',
    'Chafe',
    'Gummi',
    'Gusau',
    'Kaura Namoda',
    'Maradun',
    'Maru',
    'Shinkafi',
    'Talata Mafara',
    'Zurmi',
  ],
  'Federal Capital Territory': [
    'Abaji',
    'Bwari',
    'Gwagwalada',
    'Kuje',
    'Kwali',
  ],
};